import Link from 'next/link';
import { dropDetail } from '@/lib/deipo/repositories/admin';
import { updateDrop } from '@/app/admin/actions';
import { AdminForm } from '@/components/admin/form';
import { GeneralFields } from '@/components/admin/general-fields';
import { Field, Area, Check } from '@/components/admin/fields';
import { Inventory, Audit } from '@/components/admin/summary';
import { MediaUpload } from '@/components/admin/media-upload';
import { readiness, utcToGuatemala, fromMinorUnits } from '@/lib/deipo/validation';
export default async function Editor({params}: {params:Promise<{id:string}>}) {
 const {id}=await params; const data=await dropDetail(id); const d=data.drop; const disabled=data.role==='operator'; const action=(op:string)=>updateDrop.bind(null,id,op); const checks=readiness(d); const ready=checks.every(([,ok])=>ok);
 return <main id="main" className="admin-workspace"><div className="admin-title"><div><p className="eyebrow">DROP {String(d.number).padStart(3,'0')} / {d.lifecycle_status}</p><h1>{d.name}</h1></div><Link href={`/admin/drops/${id}/preview`}>Preview autenticado</Link></div>{disabled && <p>Acceso de lectura. Las operaciones requieren founder o admin.</p>}
 <nav className="admin-filters" aria-label="Secciones del drop">{['general','inventory','sales','schedule','fulfillment','content','packaging','publishing'].map(s=><a key={s} href={`#${s}`}>{s}</a>)}</nav>
 <section id="general"><h2>General</h2><AdminForm action={action('general')} disabled={disabled}><GeneralFields drop={d} /></AdminForm></section>
 <section id="inventory"><h2>Inventario</h2><p>{data.inventory.total_sold} / {d.capacity} SOLD · {data.inventory.available} disponibles</p><Inventory value={data.inventory} /><p className="caption">Derivado de la base de datos. Online y held permanecen en cero en Sprint 01.</p></section>
 <section id="sales"><h2>Preventa confirmada</h2><AdminForm action={action('sale')} label="Registrar venta confirmada" disabled={disabled}><div className="admin-fields"><Field label="Cantidad" name="quantity" type="number" min="1" max={data.inventory.available ?? 0} required /><Field label="Fuente" name="source" required /><Field label="Confirmada el (Guatemala; vacío = ahora)" name="confirmed_at" type="datetime-local" /><Area label="Nota opcional" name="note" /></div></AdminForm>
 <ul className="admin-list">{data.sales.map(s=><li key={s.id}><div><strong>{s.quantity} unidades · {s.source}</strong><p>{utcToGuatemala(s.confirmed_at).replace('T',' ')} · {s.note}</p>{s.voided_at ? <p>ANULADA · {s.void_reason}</p> : <AdminForm action={action('void')} label="Anular venta" confirm="La venta quedará anulada con este motivo; el historial se conserva." disabled={disabled}><input type="hidden" name="id" value={s.id} /><Field label="Motivo de anulación" name="reason" required /></AdminForm>}</div></li>)}</ul></section>
 <section id="schedule"><h2>Schedule</h2><p>America/Guatemala · 24 horas. No se generan fechas automáticamente.</p><AdminForm action={action('schedule')} disabled={disabled}><div className="admin-fields"><Field label="Apertura" name="orders_open_at" type="datetime-local" defaultValue={utcToGuatemala(d.orders_open_at)} /><Field label="Cierre" name="orders_close_at" type="datetime-local" defaultValue={utcToGuatemala(d.orders_close_at)} /><Field label="Fecha de entrega" name="fulfillment_date" type="date" defaultValue={d.fulfillment_date ?? ''} /><Field label="Label del día" name="fulfillment_day_label" defaultValue={d.fulfillment_day_label ?? ''} /></div></AdminForm></section>
 <section id="fulfillment"><h2>Fulfillment</h2><AdminForm action={action('fulfillment')} disabled={disabled}><Check label="Delivery" name="delivery_enabled" checked={d.delivery_enabled} /><Check label="Pickup" name="pickup_enabled" checked={d.pickup_enabled} /><Field label="Lugar / instrucciones de pickup" name="pickup_label" defaultValue={d.pickup_label ?? ''} /></AdminForm>
 <h3>Horarios</h3><p>La capacidad de horario no reserva inventario global.</p>{[...data.slots,null].map((s,index)=><details key={s?.id ?? 'new'} open={!s}><summary>{s ? `${s.starts_at.slice(0,5)} — ${s.ends_at.slice(0,5)} / ${s.is_enabled?'activo':'deshabilitado'}`:'Agregar horario'}</summary><AdminForm action={action('slot')} disabled={disabled}><input type="hidden" name="id" value={s?.id ?? ''} /><div className="admin-fields"><Field label="Inicio" name="starts_at" type="time" required defaultValue={s?.starts_at} /><Field label="Fin" name="ends_at" type="time" required defaultValue={s?.ends_at} /><Field label="Capacidad (opcional)" name="capacity" type="number" min="1" defaultValue={s?.capacity ?? ''} /><Field label="Orden" name="sort_order" type="number" min="0" defaultValue={s?.sort_order ?? index} /></div><Check label="Habilitado" name="is_enabled" checked={s?.is_enabled ?? true} /></AdminForm></details>)}
 <h3>Zonas de entrega</h3><p>Tarifa vacía = por confirmar. 0 = gratis.</p>{[...data.zones,null].map((z,index)=><details key={z?.id ?? 'new'} open={!z}><summary>{z ? `${z.label} / ${z.is_enabled?'activa':'deshabilitada'}`:'Agregar zona'}</summary><AdminForm action={action('zone')} disabled={disabled}><input type="hidden" name="id" value={z?.id ?? ''} /><div className="admin-fields"><Field label="Código" name="code" required defaultValue={z?.code} /><Field label="Nombre de zona" name="label" required defaultValue={z?.label} /><Field label="Tarifa GTQ" name="fee" inputMode="decimal" defaultValue={z?.fee_minor == null ? '' : fromMinorUnits(z.fee_minor)} /><Field label="Orden" name="sort_order" type="number" min="0" defaultValue={z?.sort_order ?? index} /></div><Check label="Habilitada" name="is_enabled" checked={z?.is_enabled ?? true} /></AdminForm></details>)}</section>
 <section id="content"><h2>Contenido incluido</h2>{[...data.items,null].map((item,index)=><details key={item?.id ?? 'new'} open={!item}><summary>{item?.name ?? 'Agregar alimento incluido'}</summary><AdminForm action={action('item')} disabled={disabled}><input type="hidden" name="id" value={item?.id ?? ''} /><Field label="Nombre" name="name" required defaultValue={item?.name} /><Area label="Descripción" name="description" value={item?.description} /><Field label="Orden" name="sort_order" type="number" min="0" defaultValue={item?.sort_order ?? index} /><Check label="Habilitado" name="is_enabled" checked={item?.is_enabled ?? true} /></AdminForm></details>)}</section>
 <section id="packaging"><h2>Media y packaging</h2><p>Hero activo: {d.hero_image_path || 'Sin hero'}</p><MediaUpload id={id} number={d.number} disabled={disabled} />{data.media.map(m=><details key={m.id}><summary>{m.kind} / {m.sort_order} / {m.label || m.path} / {m.is_enabled?'activo':'deshabilitado'}</summary><AdminForm action={action('media')} disabled={disabled}><input type="hidden" name="id" value={m.id} /><Field label="Texto alternativo" name="alt_text" defaultValue={m.alt_text ?? ''} /><Field label="Label" name="label" defaultValue={m.label ?? ''} /><Field label="Orden" name="sort_order" type="number" min="0" defaultValue={m.sort_order} readOnly={m.kind==='hero'} /><Check label="Habilitado" name="is_enabled" checked={m.is_enabled} /></AdminForm></details>)}</section>
 <section id="publishing"><h2>Publishing</h2><ul className="admin-checklist">{checks.map(([label,ok])=><li key={label}>{ok?'LISTO':'PENDIENTE'} · {label}</li>)}</ul><p>El servidor verifica también inventario y existencia del hero. Packaging es opcional.</p><div className="admin-actions"><AdminForm action={action('publish')} label="Publicar" confirm="Publicar permite asignar el drop al storefront. No lo asigna automáticamente." disabled={disabled || !ready || ['archived','cancelled'].includes(d.lifecycle_status)} /><AdminForm action={action('scheduled')} label="Programar" confirm="Marcar el drop como programado; podrá asignarse como NEXT." disabled={disabled || !ready || d.lifecycle_status!=='draft'} />
 {(['current','next'] as const).map(slot=><div key={slot}><p>{slot.toUpperCase()}: {data.config[`${slot}_drop_id`] === id ? 'Este drop' : 'No asignado a este drop'}</p><AdminForm action={action(slot)} label={`Asignar ${slot.toUpperCase()}`} confirm={`Cambiar ${slot.toUpperCase()} afecta el storefront público. Confirmá esta asignación.`} disabled={disabled || (slot==='current'?d.lifecycle_status!=='published':!['published','scheduled'].includes(d.lifecycle_status))} />{data.config[`${slot}_drop_id`]===id && <AdminForm action={action(`clear-${slot}`)} label={`Quitar ${slot.toUpperCase()}`} confirm={`Quitar la asignación ${slot.toUpperCase()} del storefront.`} disabled={disabled} />}</div>)}
 <AdminForm action={action('archived')} label="Archivar" confirm="Archivar es permanente. Primero quitá las asignaciones CURRENT/NEXT." disabled={disabled || ['archived','cancelled'].includes(d.lifecycle_status)} /><AdminForm action={action('cancelled')} label="Cancelar drop" confirm="Cancelar es permanente. Primero quitá las asignaciones CURRENT/NEXT." disabled={disabled || ['archived','cancelled'].includes(d.lifecycle_status)} /></div></section>
 <section><h2>Auditoría del drop</h2><Audit rows={data.audit} /></section></main>;
}
