import test from 'node:test';
import assert from 'node:assert/strict';
import { toMinorUnits, fromMinorUnits, guatemalaToUTC, utcToGuatemala, friendlyError } from '../src/lib/deipo/validation';
import { getSiteMode } from '../src/lib/site-mode';
import { mapStorefrontDrop } from '../src/lib/deipo/storefront-mapper';
import { getDropStatus } from '../src/lib/drop';
const payload = {id:'drop-test',number:2,slug:'qa',name:'QA',tagline:null,description:null,currency:'GTQ',price_minor:17500,capacity:80,prelaunch_sold_units:13,total_sold:13,online_sold_units:0,held_units:0,available:67,low_stock_threshold:8,availability:'active',orders_open_at:'2030-01-01T06:00:00Z',orders_close_at:'2030-01-02T05:59:00Z',fulfillment_date:'2030-01-02',fulfillment_day_label:null,delivery_enabled:true,pickup_enabled:true,pickup_label:null,hero_image_path:'drop-2/hero/qa.webp',items:[],slots:[],packaging_frames:[],delivery_zones:[{id:'zone',label:'TBD',fee_minor:null}]};
test('money parses integer minor units without rounding user input',()=>{assert.equal(toMinorUnits('175.01'),17501);assert.equal(toMinorUnits('0.10'),10);assert.equal(fromMinorUnits(17501),'175.01');for(const bad of ['1.001','-1','1e3','NaN','9007199254740992'])assert.throws(()=>toMinorUnits(bad));});
test('Guatemala conversion is explicit and rejects rollover dates',()=>{assert.equal(guatemalaToUTC('2030-01-01T00:00'),'2030-01-01T06:00:00.000Z');assert.equal(utcToGuatemala('2030-01-01T06:00:00Z'),'2030-01-01T00:00');assert.equal(guatemalaToUTC(''),null);assert.throws(()=>guatemalaToUTC('2030-02-30T12:00'));});
test('production site mode cannot be overridden by preview queries',()=>{const previous=process.env.NEXT_PUBLIC_SITE_MODE;try{process.env.NEXT_PUBLIC_SITE_MODE='production';for(const mode of ['preview','customer-preview','production'])assert.equal(getSiteMode({mode}),'production');}finally{if(previous===undefined)delete process.env.NEXT_PUBLIC_SITE_MODE;else process.env.NEXT_PUBLIC_SITE_MODE=previous;}});
test('customer DTO preserves null fees, no slots, optional packaging and strips private fields',()=>{const drop=mapStorefrontDrop({...payload,admin_profiles:'private',source:'private',note:'private'},'https://example.supabase.co');assert.equal(drop.sold,13);assert.equal(drop.fulfillment.zones[0].fee,null);assert.equal(drop.packagingFrames.length,0);assert.equal(drop.fulfillment.slots.length,0);assert.equal(drop.price,175);assert.ok(!JSON.stringify(drop).includes('private'));assert.equal(drop.source,'production');});
test('mapper rejects malformed inventory instead of supplying fixture scarcity',()=>{assert.throws(()=>mapStorefrontDrop({...payload,available:80},'https://example.supabase.co'));assert.throws(()=>mapStorefrontDrop({...payload,total_sold:81},'https://example.supabase.co'));assert.throws(()=>mapStorefrontDrop({...payload,hero_image_path:'https://other.test/image.png'},'https://example.supabase.co'));});
test('zero availability due to held inventory is not sold out',()=>{const drop=mapStorefrontDrop({...payload,prelaunch_sold_units:40,total_sold:40,held_units:40,available:0},'https://example.supabase.co');assert.notEqual(getDropStatus(drop,Date.parse('2030-01-01T12:00:00Z')),'sold_out');});
test('known DB errors are translated without leaking SQL',()=>{assert.match(friendlyError({code:'23505',message:'drops_number_key'}),/número/);assert.match(friendlyError({message:'Confirmed pre-launch sales would exceed drop capacity'}),/inventario/);assert.ok(!friendlyError({message:'secret database string'}).includes('secret'));});

// File size/type checks run before any upload, independently of the Storage API.
import { validateMedia } from '../src/lib/deipo/media';
test('storage accepts supported images through 15 MB and rejects other MIME and oversized files',()=>{validateMedia({type:'image/webp',size:15*1024*1024});assert.throws(()=>validateMedia({type:'image/svg+xml',size:100}));assert.throws(()=>validateMedia({type:'image/png',size:15*1024*1024+1}));});

test('an invalid configured site mode fails closed instead of showing demo stock',()=>{const previous=process.env.NEXT_PUBLIC_SITE_MODE;try{process.env.NEXT_PUBLIC_SITE_MODE='prod-typo';assert.equal(getSiteMode({mode:'preview'}),'production');}finally{if(previous===undefined)delete process.env.NEXT_PUBLIC_SITE_MODE;else process.env.NEXT_PUBLIC_SITE_MODE=previous;}});
