'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {DeipoLogo} from '@/components/brand/deipo-logo';
import {minorMoney,type CheckoutState} from '@/lib/deipo/checkout';
export function LiveCheckout({initial,failed=false}:{initial:CheckoutState|null;failed?:boolean}){
 const [state,setState]=useState(initial),[seconds,setSeconds]=useState(initial?.expiresAt?Math.max(0,Math.ceil((Date.parse(initial.expiresAt)-Date.parse(initial.serverTime))/1000)):0);
 const [error,setError]=useState(''),[pending,setPending]=useState(false),[method,setMethod]=useState(initial?.drop?.pickupEnabled?'pickup':'delivery');const busy=useRef(false);const mutationVersion=useRef(0);
 useEffect(()=>{if(!state?.expiresAt||state.state!=='active')return;const remaining=Date.parse(state.expiresAt)-Date.parse(state.serverTime);const started=performance.now();const timer=setInterval(()=>setSeconds(Math.max(0,Math.ceil((remaining-(performance.now()-started))/1000))),1000);return()=>clearInterval(timer);},[state]);
 // A poll started before a mutation must never overwrite its newer result.
 useEffect(()=>{if(state?.state!=='active')return;let stopped=false;let loading=false;const refresh=async()=>{if(document.visibilityState!=='visible'||loading||busy.current)return;loading=true;const version=mutationVersion.current;try{const r=await fetch('/api/checkout',{cache:'no-store'});const d=await r.json();if(r.ok&&!stopped&&!busy.current&&version===mutationVersion.current&&d.state)setState(d.state);}finally{loading=false;}};const timer=setInterval(()=>{void refresh().catch(()=>{});},15000);const onFocus=()=>{void refresh().catch(()=>{});};window.addEventListener('focus',onFocus);document.addEventListener('visibilitychange',onFocus);return()=>{stopped=true;clearInterval(timer);window.removeEventListener('focus',onFocus);document.removeEventListener('visibilitychange',onFocus);};},[state?.state]);
 async function submit(operation:string,form=new FormData()){if(busy.current)return;busy.current=true;mutationVersion.current+=1;setPending(true);setError('');try{form.set('operation',operation);const r=await fetch('/api/checkout',{method:'POST',body:form});const d=await r.json();if(!r.ok)throw Error(d.error);setState(d.state);setSeconds(d.state.expiresAt?Math.max(0,Math.ceil((Date.parse(d.state.expiresAt)-Date.parse(d.state.serverTime))/1000)):0);}catch(e){setError(e instanceof Error?e.message:'No pudimos confirmar la operación.');}finally{setPending(false);busy.current=false;}}
 const expired=state?.state==='expired'||(state?.state==='active'&&seconds===0);const active=state?.state==='active'&&!expired;const d=state?.drop,o=state?.order;
 return <div className="live-checkout"><header className="checkout-header"><Link href="/" aria-label="deipo. Inicio"><DeipoLogo /></Link><Link href="/">Volver al drop</Link></header><main id="main" className="live-checkout-main"><p className="eyebrow">TU DROP / RESERVA</p><h1>{expired?'Tu reserva venció.':state?.state==='released'?'Reserva cancelada.':!d?'Sin reserva activa.':o?'Pedido pendiente.':'Tu drop.'}</h1>
 {!active&&<p role="status">{failed?'No pudimos consultar tu reserva. Actualizá para reintentar.':expired?'Volvé al drop para consultar disponibilidad y reservar de nuevo.':state?.state==='released'?'Las unidades quedaron disponibles.':'Consultá el drop para continuar.'} <Link href="/">Volver al drop</Link></p>}
 {d&&<section className="live-order-summary" aria-label="Resumen"><p className="eyebrow">DROP {String(d.number).padStart(3,'0')}</p><h2>{d.name}</h2><p>{state?.quantity} × {minorMoney(d.unitPriceMinor)}</p>{active&&<p>Reserva disponible por <strong aria-live="off" data-testid="hold-countdown">{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</strong></p>}{o?<><p>{o.code} · {o.status==='pending_payment'?'Pendiente de pago':o.status}</p><p>Subtotal {minorMoney(o.subtotalMinor)} · Entrega {minorMoney(o.deliveryFeeMinor)}</p><p>Total {minorMoney(o.totalMinor)}</p><p>{o.method==='pickup'?o.pickupLabel:o.zoneLabel} · {o.fulfillmentDate} · {o.slotStart?.slice(0,5)} {o.slotEnd?`– ${o.slotEnd.slice(0,5)}`:''}</p></>:<p>Subtotal {minorMoney(d.unitPriceMinor*(state?.quantity??0))}. La tarifa de entrega se confirma al crear el pedido.</p>}</section>}
 {active&&d&&!o&&<form aria-describedby={error?'checkout-error':undefined} onSubmit={e=>{e.preventDefault();void submit('order',new FormData(e.currentTarget));}}><fieldset disabled={pending}><legend className="eyebrow">CONTACTO Y ENTREGA</legend><label>Nombre<input name="name" autoComplete="name" required maxLength={120}/></label><label>Teléfono con código de país<input name="phone" type="tel" autoComplete="tel" required placeholder="+502 5555 1234" maxLength={30}/></label><label>Correo (opcional)<input name="email" type="email" autoComplete="email" maxLength={254}/></label><label>Forma de entrega<select name="method" value={method} onChange={e=>setMethod(e.target.value)}>{d.pickupEnabled&&<option value="pickup">Pickup · {d.pickupLabel}</option>}{d.deliveryEnabled&&<option value="delivery">Delivery</option>}</select></label>{d.slots.length>0&&<label>Horario<select name="slot_id" required defaultValue=""><option value="" disabled>Elegí un horario</option>{d.slots.map(s=><option key={s.id} value={s.id}>{s.start} – {s.end}</option>)}</select></label>}{method==='delivery'&&<><label>Zona<select name="zone_id" required defaultValue=""><option value="" disabled>Elegí una zona</option>{d.zones.map(z=><option key={z.id} value={z.id} disabled={z.feeMinor===null}>{z.label} · {z.feeMinor===null?'Tarifa por confirmar':minorMoney(z.feeMinor)}</option>)}</select></label><label>Dirección<input name="address" autoComplete="street-address" required maxLength={1000}/></label><label>Referencia (opcional)<textarea name="notes" maxLength={1000}/></label></>}<p className="caption">Fecha de entrega: {d.fulfillmentDate}. Los pagos aún no están conectados. Crear el pedido conserva la reserva hasta su vencimiento; no confirma una compra.</p><button className="button" disabled={pending||!d.onlineOrderingEnabled}>{pending?'GUARDANDO…':'CREAR PEDIDO PENDIENTE'}</button></fieldset></form>}
 {o&&active&&<p role="status">Pendiente de pago. Los pagos aún no están conectados. Tu compra no está confirmada y la reserva vence a la hora indicada.</p>}
 {error&&<p id="checkout-error" role="alert" className="field-error">{error}</p>}
 {active&&<button className="text-link" disabled={pending} onClick={()=>void submit(o?'cancel':'release')}>{pending?'PROCESANDO…':o?'Cancelar pedido pendiente':'Liberar reserva'}</button>}
 </main></div>;
}
