import {orderDetail} from '@/lib/deipo/repositories/orders';
import {AdminForm} from '@/components/admin/form';
import {Field} from '@/components/admin/fields';
import {cancelAdminOrder} from '@/app/admin/actions';
import {minorMoney} from '@/lib/deipo/checkout';
import {utcToGuatemala} from '@/lib/deipo/validation';
export default async function Order({params}:{params:Promise<{id:string}>}){
 const {id}=await params,{order:o,items,events,role}=await orderDetail(id);const date=(s:string|null)=>utcToGuatemala(s).replace('T',' ')||'—';
 return <main id="main" className="admin-workspace"><div className="admin-title"><div><p className="eyebrow">ORDER / {o.effective_status}</p><h1>{o.order_code}</h1><p>{date(o.created_at)} · Guatemala</p></div></div><section><h2>Cliente</h2><p>{o.customer_name}</p><p>{o.customer_phone}</p><p>{o.customer_email||'Sin correo'}</p></section><section><h2>Drop</h2>{items.map(i=><div key={i.id}><p>DROP {String(i.snapshot_drop_number).padStart(3,'0')} · {i.snapshot_name}</p><p>{i.quantity} × {minorMoney(i.unit_price_minor)} = {minorMoney(i.line_total_minor??0)}</p></div>)}</section><section><h2>Entrega</h2><p>{o.fulfillment_method} · {o.fulfillment_date}</p><p>{o.slot_start?.slice(0,5)} {o.slot_end?`– ${o.slot_end.slice(0,5)}`:''}</p><p>{o.pickup_label||o.delivery_zone_label}</p><p>{o.delivery_address}</p><p>{o.delivery_notes}</p><p>Tarifa: {minorMoney(o.delivery_fee_minor??0)}</p></section><section><h2>Total</h2><p>Subtotal {minorMoney(o.subtotal_minor??0)}</p><p>Entrega {minorMoney(o.delivery_fee_minor??0)}</p><strong>{minorMoney(o.total_minor??0)}</strong></section><section><h2>Inventario</h2><p>Hold: {o.hold_status==='active'&&o.effective_status==='expired'?'expired (por tiempo)':o.hold_status}</p><p>Vence: {date(o.expires_at)}</p><p>Comprometido: {o.inventory_committed_at?date(o.inventory_committed_at):'No'}</p><p>Liberación posterior al compromiso: {date(o.inventory_released_at)}</p>{o.cancel_reason&&<p>Cancelación: {o.cancel_reason}</p>}{o.effective_status==='pending_payment'&&!o.inventory_committed_at&&role!=='operator'&&<AdminForm action={cancelAdminOrder.bind(null,id)} label="Cancelar pedido pendiente" confirm="El pedido se cancelará y su reserva quedará liberada. El historial se conserva."><Field label="Motivo de cancelación" name="reason" required maxLength={500}/></AdminForm>}</section><section><h2>Historial</h2><ul className="admin-list">{events.map(e=><li key={e.id}><strong>{e.event_type}</strong><span>{e.actor_kind} · {date(e.created_at)}</span></li>)}</ul></section></main>;
}
