import {test,expect} from '@playwright/test';import AxeBuilder from '@axe-core/playwright';
test.beforeEach(async({request})=>{await request.get('http://127.0.0.1:54329/reset');});
test('reserve, reload, pending order, idempotency, customer cancel, private cookie and a11y',async({page,context,request})=>{
 await page.goto('/');await page.getByRole('button',{name:'Aumentar cantidad'}).click();await page.getByRole('button',{name:'RESERVAR DROP',exact:true}).click();await expect(page).toHaveURL(/\/checkout$/);await expect(page.getByTestId('hold-countdown')).toBeVisible();
 const cookie=(await context.cookies()).find(c=>c.name==='deipo_checkout_session')!;expect(cookie.httpOnly).toBe(true);expect(cookie.sameSite).toBe('Lax');expect(cookie.path).toBe('/');expect(cookie.domain).toBe('127.0.0.1');expect(await page.evaluate(()=>document.cookie)).not.toContain(cookie.value);expect(await page.content()).not.toContain(cookie.value);expect(page.url()).not.toContain(cookie.value);
 const before=await page.getByTestId('hold-countdown').textContent();await page.waitForTimeout(1100);await page.reload();const after=await page.getByTestId('hold-countdown').textContent();expect(after!<=before!).toBe(true);
 const stats=await (await request.get('http://127.0.0.1:54329/stats')).json();expect(stats.inventory.held_units).toBe(2);expect(stats.holds[0].hash).not.toBe(cookie.value);
 await page.getByLabel('Nombre',{exact:true}).fill('Browser customer');await page.getByLabel('Teléfono con código de país').fill('+502 5555 1234');
 expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
 await page.screenshot({path:'/private/tmp/deipo-s02-checkout-desktop.png',fullPage:true});
 let releaseStalePoll!:()=>void;const holdPoll=new Promise<void>(resolve=>{releaseStalePoll=resolve;});let pollCaptured!:()=>void;const captured=new Promise<void>(resolve=>{pollCaptured=resolve;});
 await page.route('**/api/checkout',async route=>{if(route.request().method()!=='GET'){await route.continue();return;}const response=await route.fetch();pollCaptured();await holdPoll;await route.fulfill({response});});
 await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await captured;
 await page.getByRole('button',{name:'CREAR PEDIDO PENDIENTE'}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('heading',{name:'Pedido pendiente.'})).toBeVisible();await expect(page.getByText('Tu compra no está confirmada',{exact:false})).toBeVisible();
 const staleResponse=page.waitForResponse(r=>r.url().endsWith('/api/checkout')&&r.request().method()==='GET');releaseStalePoll();await (await staleResponse).finished();await page.waitForTimeout(250);await expect(page.getByRole('heading',{name:'Pedido pendiente.'})).toBeVisible();await expect(page.getByRole('button',{name:'CREAR PEDIDO PENDIENTE'})).toHaveCount(0);await page.unroute('**/api/checkout');
 const repeat=await page.evaluate(async()=>{const f=new FormData();Object.entries({operation:'order',name:'Browser customer',phone:'+50255551234',method:'pickup'}).forEach(([k,v])=>f.set(k,v));return (await fetch('/api/checkout',{method:'POST',body:f})).json();});expect(repeat.state.order.status).toBe('pending_payment');
 await page.getByRole('button',{name:'Cancelar pedido pendiente'}).click();await expect(page.getByRole('heading',{name:'Reserva cancelada.'})).toBeVisible();const end=await (await request.get('http://127.0.0.1:54329/stats')).json();expect(end.inventory.held_units).toBe(0);expect(end.inventory.total_sold).toBe(0);
});
test('mobile release, session isolation, invalid checkout and CSRF',async({page,browser,request})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/checkout');await expect(page.getByRole('heading',{name:'Sin reserva activa.'})).toBeVisible();await page.goto('/');await page.getByRole('button',{name:'RESERVAR DROP',exact:true}).click();await expect(page.getByTestId('hold-countdown')).toBeVisible();
 const other=await browser.newContext();const p=await other.newPage();await p.goto('http://127.0.0.1:3002/checkout');await expect(p.getByRole('heading',{name:'Sin reserva activa.'})).toBeVisible();await other.close();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
 expect((await request.post('/api/checkout',{headers:{Origin:'https://evil.example'},form:{operation:'release'}})).status()).toBe(403);
 await page.getByRole('button',{name:'Liberar reserva'}).click();await expect(page.getByRole('heading',{name:'Reserva cancelada.'})).toBeVisible();
});
test('countdown expires from server time without reset, and gate stays off when disabled',async({page,request})=>{
 await page.goto('/');await request.get('http://127.0.0.1:54329/close-soon');await page.getByRole('button',{name:'RESERVAR DROP',exact:true}).click();await expect(page.getByRole('heading',{name:'Tu reserva venció.'})).toBeVisible({timeout:12000});await page.reload();await expect(page.getByRole('heading',{name:'Tu reserva venció.'})).toBeVisible();const s=await (await request.get('http://127.0.0.1:54329/stats')).json();expect(s.inventory.held_units).toBe(0);
 await request.get('http://127.0.0.1:54329/reset');await request.get('http://127.0.0.1:54329/disable');await page.goto('/');await expect(page.getByText('Pedidos online todavía no habilitados.')).toBeVisible();await expect(page.getByRole('button',{name:'RESERVAR DROP',exact:true})).toHaveCount(0);
});
test('all held shows reserved, and founder can inspect and cancel an order with a reason',async({page,request})=>{
 await page.goto('/');for(let i=0;i<4;i++)await page.getByRole('button',{name:'Aumentar cantidad'}).click();await page.getByRole('button',{name:'RESERVAR DROP',exact:true}).click();await page.getByLabel('Nombre',{exact:true}).fill('Admin fixture');await page.getByLabel('Teléfono con código de país').fill('+50255551234');await page.getByRole('button',{name:'CREAR PEDIDO PENDIENTE'}).click();await expect(page.getByRole('heading',{name:'Pedido pendiente.'})).toBeVisible();
 await page.goto('/');await expect(page.getByText('CURRENTLY RESERVED.',{exact:true})).toBeVisible();await page.goto('/admin/login');await page.getByLabel('Email').fill('founder@example.test');await page.getByLabel('Contraseña').fill('fixture-password');await page.getByRole('button',{name:'Iniciar sesión',exact:true}).click();await expect(page).toHaveURL(/\/admin$/);await page.goto('/admin/orders');await expect(page.getByText('Admin fixture')).toBeVisible();await page.getByRole('link',{name:/^D-/}).click();await expect(page.getByRole('heading',{name:'Historial'})).toBeVisible();expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);await page.getByLabel('Motivo de cancelación').fill('Customer requested cancellation');await page.getByRole('button',{name:'Cancelar pedido pendiente',exact:true}).click();await page.getByRole('button',{name:'Confirmar',exact:true}).click();await expect(page.getByText('ORDER / cancelled')).toBeVisible();const s=await (await request.get('http://127.0.0.1:54329/stats')).json();expect(s.inventory.available).toBe(5);
});
test('live inventory refresh recovers released holds and HTTPS proxy sets a Secure host-only cookie',async({page,browser,request})=>{
 await page.goto('/');await expect(page.getByRole('button',{name:'RESERVAR DROP',exact:true})).toBeVisible();
 const other=await browser.newContext();const buyer=await other.newPage();await buyer.goto('http://127.0.0.1:3002/');for(let i=0;i<4;i++)await buyer.getByRole('button',{name:'Aumentar cantidad'}).click();await buyer.getByRole('button',{name:'RESERVAR DROP',exact:true}).click();await expect(buyer.getByTestId('hold-countdown')).toBeVisible();
 await page.bringToFront();await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByText('CURRENTLY RESERVED.',{exact:true})).toBeVisible({timeout:20000});
 await buyer.getByRole('button',{name:'Liberar reserva'}).click();await expect(buyer.getByRole('heading',{name:'Reserva cancelada.'})).toBeVisible();await page.bringToFront();await expect(page.getByRole('button',{name:'RESERVAR DROP',exact:true})).toBeVisible({timeout:20000});await other.close();
 const response=await request.get('/',{headers:{host:'deploy-preview-2--deipo.netlify.app','x-forwarded-proto':'https'}});const cookie=response.headers()['set-cookie'];expect(cookie).toContain('deipo_checkout_session=');expect(cookie).toMatch(/HttpOnly/i);expect(cookie).toMatch(/Secure/i);expect(cookie).toMatch(/SameSite=Lax/i);expect(cookie).not.toMatch(/Domain=/i);expect(response.headers()['cache-control']).toContain('no-store');
});
